# the name of your track or event
name = "Choose Your Dinner Adventure"

# the name of the group organizing the event
org = "Protocol Labs"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with devent organizers)
dri = "@yunigraham"

# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
website = "Coming Soon"

# the start date of the event
date = "2022-07-11"

# how many days the event lasts (1 - N)
days = 3 (Tuesday, Thursday, Friday)

# the event times (shows up in the event card)
times = "5:00 - 10:00pm"

# the event venue name (will show up on the event card - TODO)
venueName = "Choose Your Dinner Adventure"

# the event venue address (will show up on a map -- TODO)
venueAddress = "Multiple"

# the max number of attendees of the event
attendees = "Varies"


# these is unsued:
# tickets = "Waitlist"

# the "difficulty" of the event -- one of:
# ["Beginner", "Intermediate", "Advanced", "All Welcome"]
difficulty = "All Welcome"

# tags for the event, will show up as labels.
# pick 1-4
tags = ["Dinner", "Random Dinner", "Dinner adventure", "Open Dinner Reservations"]

# a color, to group key events visually. use sparingly
# color="pinky purple"

# a description of the event.
# will show up when the user clicks the event card.
description = """
Take the hassle of deciding on a dinner location away with "Choose Your Dinner Adventure!" Guests can sign up for a dinner either solo or as a small group. Spaces are limited and these bookings are not large bookings. If no one has signed up for a dinner location by the day before, the reservation will be deleted. Sign up here (placeholder til links are ready).  
"""
